apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: provider-terraform
  namespace: crossplane-system
spec:
  package: xpkg.upbound.io/upbound/provider-terraform:v0.14.1